import type { Metadata } from 'next';
import { Space_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import MUITheme from '@/components/MUITheme';

const Mono = Space_Mono({ weight: '400', subsets: ['latin'], variable: '--font-space-mono' });

export const metadata: Metadata = {
	title: 'War Three Kingdom',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={Mono.variable}>
				<MUITheme>
					<Navbar />
					{children}
				</MUITheme>
			</body>
		</html>
	);
}
