import type { Metadata } from 'next';
import { Space_Mono, Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import MUITheme from '@/components/MUITheme';
import Footer from '@/components/Footer';

const Mono = Space_Mono({ weight: '400', subsets: ['latin'], variable: '--font-space-mono' });
const Mont = Montserrat({ weight: ['400', '500'], subsets: ['latin'], variable: '--font-montserrat' });

export const metadata: Metadata = {
	title: 'War Three Kingdom',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${Mono.variable} ${Mont.variable}`}>
				<MUITheme>
					<Navbar />
					{children}
					<Footer />
				</MUITheme>
			</body>
		</html>
	);
}
